#Make test framework for push_back method
#This Makefile makes object file for testVecrot

ALLOCATOR = ../TrackingAllocator.h
SRC       = ../vector.h

testVector.o : $(ALLOCATOR) $(SRC)

.PHONY: clean
clean :
	rm *.o *.gcda *.gcno *.h.gcov *.cpp.gcov *.gcov val_log run